"""Seed the database with initial data: 28 scripts, 8 trends."""
from database import SessionLocal
from models import Script, Trend


def seed_scripts():
    db = SessionLocal()
    try:
        if db.query(Script).count() > 0:
            return
        scripts = [
            Script(title="Claude Code mudou meu workflow — e eu não sou dev sênior", hook="Um AI escreveu 80% desse código", body="Cara, sério. Três meses atrás eu tava escrevendo função por função. Hoje eu abro o Claude Code, descrevo o que eu quero em português, e ele escreve o código, testa sozinho e ainda corrige quando quebra. No projeto do cliente americano eu usei pra automatizar a geração de relatórios de viabilidade — o que levava 2 horas agora leva 10 minutos.", cta="Comenta CODE se você quer um tutorial do meu setup exato", cta_keyword="CODE", category="ferramentas", visual_format="Tela compartilhada Claude Code + facecam", source_usa="Alex Finn", adaptation_note="Adaptado para PM/dev brasileiro", caption="Claude Code não é só para quem não sabe codar — é para quem quer codar 10x mais rápito ⚡", hashtags="#claudecode #ai #produtividade #automação"),
            Script(title="Meu workflow de n8n que economiza 15 horas por semana", hook="15h economizadas toda semana com esse workflow", body="Vou mostrar o workflow de n8n que montei pro cliente americano. Webhook entra, n8n processa, consulta ClickUp, gera draft no Missive, cria tarefa e manda pro Slack. Tudo automático. Antes uma pessoa fazia isso manualmente. Agora é zero toque humano.", cta="Comenta N8N que eu te mando o template", cta_keyword="N8N", category="ferramentas", visual_format="Tela n8n mostrando workflow + facecam", source_usa="Nate Herk", adaptation_note="Foco no resultado de negócio", caption="Workflow de n8n que eliminou 15h de trabalho manual POR SEMANA 🔄", hashtags="#n8n #automação #ia #produtividade #workflow"),
            Script(title="Cursor vs. Claude Code: eu testei os dois por 30 dias", hook="Cursor ✗ Claude Code — quem ganhou?", body="Fiz teste de 30 dias. Cursor é melhor pra quem já programa — autocomplete com esteroides. Claude Code é melhor pra delegar tarefas maiores. Eu uso os dois: Cursor pro dia a dia, Claude Code quando preciso de algo do zero.", cta="Qual você usa? Comenta aí", cta_keyword="CURSOR", category="ferramentas", visual_format="Tela dividida Cursor vs Claude Code + facecam", source_usa="ByteGrad + Alex Finn", adaptation_note="Visão imparcial de quem usou os dois", caption="30 dias testando Cursor e Claude Code em projetos reais 🔥", hashtags="#cursor #claudecode #vibecoding #ia #dev"),
            Script(title="3 ferramentas de IA que me fazem parecer uma equipe", hook="Sou uma pessoa só. Mas o cliente americano acha que eu sou uma equipe.", body="Culpa é dessas 3 ferramentas: n8n (automação de graça), Claude Code (escreve código sozinho), e TheHandover (gera relatórios em 5 min). Uma pessoa só. 3 ferramentas. Trabalho de equipe inteira.", cta="Comenta EQUIPE que eu te mostro meu stack completo", cta_keyword="EQUIPE", category="ferramentas", visual_format="Facecam + tela mostrando 3 ferramentas", source_usa="Matt Wolfe + Superhuman AI", adaptation_note="Cada ferramenta tem caso de uso do projeto americano", caption="Sou uma pessoa só. Mas o cliente americano acha que eu sou uma equipe 🎯", hashtags="#ia #automação #produtividade #n8n #claudecode"),
            Script(title="Por que eu parei de vender bot de WhatsApp", hook="Parei de vender bot de WhatsApp e minha renda triplicou", body="Vendia bot pra comércio de BH. Mercado saturado, todo mundo brigando por preço. Parei. Foquei em automação end-to-end com IA pra empresas que precisam de resultado. Agora cobro 5x mais e o cliente fica feliz de pagar. O diferencial não é a ferramenta, é o resultado.", cta="Comenta RESULTADO que eu te conto como fiz essa transição", cta_keyword="RESULTADO", category="mindset", visual_format="Facecam close-up, tom sério", source_usa="Greg Isenberg", adaptation_note="História real de pivot", caption="Parei de vender bot de WhatsApp e minha renda triplicou 💡", hashtags="#mindset #negócio #ia #automação #empreendedorismo"),
            Script(title="High Agency: o diferencial que ninguém fala", hook="High Agency é o que separa quem ganha bem de quem não sai do lugar", body="Tenho 23 anos e trabalho com cliente americano. Não sou o melhor dev — tenho High Agency. Vejo problema e resolvo em vez de esperar. Cliente pediu automação de email, eu entreguei + relatório inteligente + integração com calendário. Sozinho. Em uma semana.", cta="Comenta AGENCY que eu te mando o framework", cta_keyword="AGENCY", category="mindset", visual_format="Facecam close-up, gestos", source_usa="Shreyas Doshi", adaptation_note="Conceito de Shreyas aplicado à experiência real", caption="High Agency é o que separa quem ganha bem de quem não sai do lugar ⚡", hashtags="#highagency #mindset #pm #produto #carreira"),
            Script(title="Como precifico um projeto de automação de IA", hook="Quanto cobrar por um projeto de automação com IA?", body="Fórmula: calcula horas economizadas por mês × valor/hora do cliente × 12 ÷ 3. Minha automação economiza 20h/semana. A $50/h, são $52k/ano. Divido por 3: ~$17k. É nessa faixa que cobro.", cta="Comenta PREÇO que eu te mando a planilha", cta_keyword="PREÇO", category="mindset", visual_format="Tela planilha/cálculo + facecam", source_usa="Nate Herk", adaptation_note="Fórmula real baseada em experiência", caption="Quanto cobrar por automação com IA? 💰 Fórmula real", hashtags="#precificação #consultoria #ia #automação #negócio"),
            Script(title="5 coisas que aprendi negociando com cliente americano", hook="Negociar com americano é diferente. Muito diferente.", body="Cinco lições: 1) valorizam resultado mensurável, 2) comunicação direta, 3) entrega antes do prazo, 4) mostra trabalho em progresso, 5) fale a língua deles — ROI, KPI, efficiency. Meu inglês C1 ajuda, mas o que fecha é mostrar que entende de negócio.", cta="Comenta USA que eu te conto como consegui meu primeiro cliente americano", cta_keyword="USA", category="mindset", visual_format="Facecam, tom de conselho", source_usa="Experiência real", adaptation_note="Experiência autêntica de trabalho internacional", caption="5 lições de 1 ano negociando com cliente americano 🇺🇸", hashtags="#clienteinternacional #negociação #english #b2b"),
            Script(title="O que aprendi atendendo Wellhub, UFC e FoodToSave", hook="2 anos atendendo empresa de peso me ensinaram mais que 4 anos de faculdade", body="Trabalhei 2 anos na SKEPS. Aprendi: empresa grande quer resultado seguro, comunicação > código, quem entende de negócio cobra mais. Saí de dev que só codava pra PM que entende de CAC, churn, ticket médio e ICP.", cta="Comenta SKEPS que eu te conto as histórias", cta_keyword="SKEPS", category="cases", visual_format="Facecam, logos como overlay", source_usa="Lenny's Newsletter", adaptation_note="Cases reais sem expor dados sensíveis", caption="2 anos na SKEPS atendendo Wellhub, UFC, FoodToSave 🏢", hashtags="#carreira #pm #dev #consultoria #experiência"),
            Script(title="Como o bot do Banco Rendimento me ensinou sobre produto", hook="Um bot de WhatsApp me ensinou mais sobre produto do que qualquer livro", body="Desenvolvi o Brena pro Banco Rendimento — bot que faz Pix, paga contas, consulta saldo. Usa Gemini 1.5 + Vertex AI. Aprendi: usuário não quer interface bonita — quer resolver em 10 segundos. Produto bom é produto que resolve rápido.", cta="Comenta BRENA que eu te mostro como funciona por dentro", cta_keyword="BRENA", category="cases", visual_format="Tela bot funcionando no WhatsApp + facecam", source_usa="Case real", adaptation_note="Case real do projeto Brena", caption="Um bot de WhatsApp me ensinou mais sobre produto do que qualquer livro 📱", hashtags="#produto #ia #whatsapp #bot #fintech"),
            Script(title="FairSet: como eu usei IA pra balancear times de vôlei", hook="Minha IA balanceia times de vôlei melhor que qualquer técnico", body="Criei o FairSet — plataforma que usa IA pra inferir nível técnico dos jogadores e balancear times. React, NestJS, PostgreSQL e ML. Projeto pessoal que virou produto real.", cta="Comenta FAIRSET que eu te mostro a demo", cta_keyword="FAIRSET", category="cases", visual_format="Tela FairSet + facecam", source_usa="Case real", adaptation_note="Projeto pessoal demonstra habilidade ML+produto", caption="Minha IA balanceia times de vôlei melhor que qualquer técnico 🏐", hashtags="#ia #machinelearning #produto #react #nestjs"),
            Script(title="Vibe Coding vai explodir no Brasil em 2025", hook="Vibe coding vai mudar como software é feito no Brasil", body="Você descreve o que quer em português e a IA escreve o código. Vai explodir no Brasil porque resolve falta de dev sênior, acelera 10x a entrega, e qualquer um que pensa bem consegue construir. Eu uso todo dia no projeto americano.", cta="Comenta VIBE que eu te mostro meu workflow", cta_keyword="VIBE", category="trends", visual_format="Tela vibe coding em ação + facecam", source_usa="Fireship + Alex Finn", adaptation_note="Tendência dos EUA contextualizada pro BR", caption="Vibe coding vai explodir no Brasil em 2025 🚀", hashtags="#vibecoding #ia #desenvolvimento #tendência #brasil"),
            Script(title="Como uso Gemini 1.5 pra processar documentos em massa", hook="Gemini 1.5 processou 500 páginas de documento em 30 segundos", body="Gemini 1.5 tem janela de contexto gigante. Usei pra processar 500 páginas de documentação do cliente americano. Em 30 segundos resumiu, extraiu action items e identificou inconsistências. O que levaria 2 dias, Gemini fez em 30 segundos.", cta="Comenta GEMINI que eu te mostro o prompt", cta_keyword="GEMINI", category="ferramentas", visual_format="Tela Gemini processando documento + facecam", source_usa="TLDR AI + Google AI blog", adaptation_note="Case real de uso de Gemini no projeto Brena", caption="Gemini 1.5 processou 500 páginas em 30 segundos 📄", hashtags="#gemini #google #ia #vertexai #produtividade"),
            Script(title="AI Agents: como ganhar dinheiro com isso", hook="AI Agents vão criar uma nova categoria de renda. E ninguém no Brasil tá falando.", body="AI Agent é programa que usa IA pra tomar decisões e executar ações sozinho. Como ganhar dinheiro? Monta agentes sob medida pra empresas. Um agente de atendimento custa 2-5 mil pra implementar e economiza 10-20 mil/ano. Montei 3 pro cliente americano.", cta="Comenta AGENT que eu te mostro como montar seu primeiro", cta_keyword="AGENT", category="trends", visual_format="Diagrama AI Agent + facecam", source_usa="Nate Herk + Rowan Cheung", adaptation_note="Tendência emergente contextualizada", caption="AI Agents vão criar uma nova categoria de renda 💰", hashtags="#aiagents #ia #automação #renda #consultoria"),
            Script(title="Como eu documento uma reunião em 30 segundos com IA", hook="Documento reunião em 30 segundos. Antes levava 30 minutos.", body="Gravo a reunião, mando pro Whisper, IA transcreve e gera: resumo, decisões, action items com responsáveis, e próximos passos. Tudo em 30 segundos. Antes gastava 30 minutos escrevendo. No projeto americano, economizo 5 horas/semana só em documentação.", cta="Comenta DOCS que eu te mando o template", cta_keyword="DOCS", category="workflows", visual_format="Tela transcrição → resumo + facecam", source_usa="Superhuman AI + Lenny's Newsletter", adaptation_note="Workflow real de PM", caption="Documento reunião em 30 segundos com IA ⏱️", hashtags="#pm #produtividade #ia #documentação #whisper"),
            Script(title="Meu stack de produtividade 2025", hook="Meu stack de produtividade que me faz parecer uma equipe", body="Uso todo dia: Claude Code (coding), n8n (automação), ClickUp (gestão), Missive (email), TheHandover (relatórios), Notion (docs). Tudo conectado via webhooks e APIs. Uma pessoa só com o poder de uma equipe.", cta="Comenta STACK que eu detalho cada ferramenta", cta_keyword="STACK", category="workflows", visual_format="Tela mostrando stack + facecam", source_usa="Matt Wolfe", adaptation_note="Stack real usado no dia a dia", caption="Meu stack de produtividade 2025 🛠️", hashtags="#produtividade #stack #ia #automação #dev"),
            Script(title="3 formas de usar IA como PM que ninguém te conta", hook="3 formas de usar IA como PM que ninguém fala", body="1) Análise de dados: joga CSV pro Claude e pede insights. 2) Documentação: reunião transcrita automaticamente. 3) Priorização: descreve contexto e pede pro IA sugerir priorização usando framework RICE. Uso as 3 no projeto americano.", cta="Comenta PM que eu te mando os prompts", cta_keyword="PM", category="workflows", visual_format="Tela mostrando 3 usos + facecam", source_usa="Lenny's Newsletter", adaptation_note="Focado em PM brasileiro", caption="3 formas de usar IA como PM que ninguém te conta 🧠", hashtags="#pm #ia #produtividade #produto #gestão"),
            Script(title="Como uso ClickUp + IA pra gerenciar projeto sozinho", hook="Gerencio um projeto americano sozinho com esse setup de ClickUp", body="Transformei o ClickUp do cliente numa máquina. Cada tarefa tem automação: quando muda de status, dispara webhook pro n8n. Processa, atualiza Missive com draft de email, notifica no Slack. Tudo automático. Eu só defino as regras uma vez.", cta="Comenta SETUP que eu te mando o esquema", cta_keyword="SETUP", category="workflows", visual_format="Tela ClickUp automações + facecam", source_usa="Jeff Su", adaptation_note="Mostra o 'como' por trás da magia", caption="Gerencio um projeto americano sozinho com ClickUp + IA 🤖", hashtags="#clickup #produtividade #ia #pm #automação"),
            Script(title="Como testo meus prompts de IA antes de produção", hook="Você precisa saber disso sobre prompts de IA", body="Antes de colocar qualquer prompt em produção, eu testo em 3 cenários: melhor caso, pior caso, e caso inesperado. Só depois de passar nos 3 é que vai pro workflow. No projeto do cliente americano, isso me salvou de gerar relatórios errados várias vezes.", cta="Comenta PROMPT que eu te mando o framework", cta_keyword="PROMPT", category="workflows", visual_format="Tela comparando prompts + facecam", source_usa="Adaptação original", adaptation_note="Framework de teste de prompts", caption="Como testo meus prompts de IA antes de colocar em produção ⚡", hashtags="#ia #produtividade #automação #dev #pm"),
            Script(title="Por que escolhi NestJS pro meu projeto de IA", hook="Por que eu uso NestJS em vez de Express ou Fastify", body="NestJS tem arquitetura modular, injeção de dependência nativa, e suporte a TypeScript de primeira classe. Pro FairSet e pro cliente americano, isso significa: código organizado, testável, e escalável. Quando preciso adicionar uma nova feature, é plug and play.", cta="Comenta NESTJS que eu te mostro a arquitetura", cta_keyword="NESTJS", category="ferramentas", visual_format="Tela código NestJS + facecam", source_usa="Fireship", adaptation_note="Opinião técnica baseada em uso real", caption="Por que eu escolhi NestJS pro meu projeto de IA 🏗️", hashtags="#nestjs #dev #typescript #backend #ia"),
            Script(title="Como uso Notion + IA pra gerenciar 3 projetos", hook="Notion + IA = gestão de 3 projetos sem loucura", body="Uso Notion como central de comando. Cada projeto tem sua página, com banco de dados de tarefas, docs, e reuniões. A IA do Notion resume docs longos, sugere próximos passos, e até escreve updates de status. Conecto com n8n pra sincronizar com ClickUp.", cta="Comenta NOTION que eu te mando o template", cta_keyword="NOTION", category="workflows", visual_format="Tela Notion + facecam", source_usa="Superhuman AI", adaptation_note="Workflow real de gestão múltipla", caption="Notion + IA = gestão de 3 projetos sem loucura 📋", hashtags="#notion #produtividade #ia #pm #gestão"),
            Script(title="O erro mais comum de quem começa com IA", hook="Esse erro custa caro pra quem começa com IA", body="O erro mais comum é querer usar IA pra TUDO de uma vez. Começa com uma coisa. Automatiza um processo que você faz todo dia. Quando estiver funcionando bem, pega o próximo. No projeto americano, eu comecei só com automação de email. Hoje tem 15 automações rodando.", cta="Comenta ERRO que eu te ajudo a começar do jeito certo", cta_keyword="ERRO", category="mindset", visual_format="Facecam, tom de conselho", source_usa="Shreyas Doshi", adaptation_note="Conselho prático baseado em experiência", caption="O erro mais comum de quem começa com IA ❌", hashtags="#ia #mindset #produto #carreira #pm"),
            Script(title="Como eu aprendi inglês C1 sem sair de BH", hook="Inglês C1 sem sair de BH — como eu fiz", body="Não fiz intercâmbio. Consumi conteúdo em inglês todo dia: YouTube tech, newsletters, podcasts. Pratiquei escrevendo documentação em inglês pro cliente americano. O segredo: imersão diária, mesmo que 30 minutos. Em 2 anos, passei de intermediário pra C1.", cta="Comenta INGLÊS que eu te conto minha rotina", cta_keyword="INGLÊS", category="mindset", visual_format="Facecam, tom inspirador", source_usa="Experiência pessoal", adaptation_note="História real de aprendizado", caption="Inglês C1 sem sair de BH 🇬🇧 Minha rotina", hashtags="#inglês #carreira #dev #remoto #clienteinternacional"),
            Script(title="Replit + IA: programar do celular é real", hook="Programar do celular com IA? É real e funciona", body="Replit tem agente de IA integrado. Você descreve o que quer, ele escreve o código, testa e deploya. Tudo do celular. Usei pra fazer hotfix no projeto americano enquanto tava no uber. Não é pra trabalhar 100% do celular, mas pra emergências é salvador.", cta="Comenta REPLIT que eu te mostro como funciona", cta_keyword="REPLIT", category="ferramentas", visual_format="Tela Replit no celular + facecam", source_usa="Replit blog", adaptation_note="Uso prático e inesperado", caption="Programar do celular com IA? É real e funciona 📱", hashtags="#replit #ia #dev #mobile #produtividade"),
            Script(title="Como uso RAG pra dar superpoderes pro meu produto", hook="RAG é o segredo por trás dos melhores produtos de IA", body="RAG (Retrieval Augmented Generation) é quando a IA consulta seus documentos antes de responder. Usei no FairSet pra consultar regras de balanceamento, e no cliente americano pra consultar histórico de relatórios. Resultado: respostas precisas baseadas em DADOS REAIS, não alucinações.", cta="Comenta RAG que eu te explico passo a passo", cta_keyword="RAG", category="ferramentas", visual_format="Diagrama RAG + facecam", source_usa="TLDR AI", adaptation_note="Explicação prática de RAG com cases reais", caption="RAG é o segredo por trás dos melhores produtos de IA 🧠", hashtags="#rag #ia #llm #produto #dev #machinelearning"),
            Script(title="Do Zero a Primeiro Cliente Internacional em 6 Meses", hook="Como eu consegui meu primeiro cliente americano em 6 meses", body="Passo a passo: Mês 1-2: construí portfólio com projetos pessoais (FairSet, Brena). Mês 3-4: comecei a postar conteúdo em inglês no LinkedIn. Mês 5: uma agência me encontrou e me indicou pro cliente. Mês 6: primeiro contrato assinado. O segredo: portfólio + conteúdo + networking.", cta="Comenta CLIENTE que eu te conto cada passo", cta_keyword="CLIENTE", category="cases", visual_format="Timeline visual + facecam", source_usa="Greg Isenberg", adaptation_note="Roadmap real do próprio Gil", caption="Do Zero a Primeiro Cliente Internacional em 6 Meses 🌎", hashtags="#clienteinternacional #freelance #ia #dev #carreira"),
            Script(title="O que é um Product Manager que programa?", hook="PM que programa é um unicórnio no mercado brasileiro", body="Sou PM e dev. Isso me dá superpoderes: consigo prototipar sozinho, entender limites técnicos, e comunicar com devs na língua deles. No projeto americano, isso significa que eu entrego features completas sem depender de ninguém. É o diferencial mais valioso que tenho.", cta="Comenta UNICÓRNIO que eu te explico essa combinação", cta_keyword="UNICÓRNIO", category="mindset", visual_format="Facecam + diagrama PM×Dev", source_usa="Lenny's Newsletter", adaptation_note="Posicionamento único do Gil", caption="PM que programa é um unicórnio no mercado brasileiro 🦄", hashtags="#pm #dev #produto #carreira #diferencial"),
            Script(title="Como valido uma ideia de produto em 48 horas", hook="Valido ideia de produto em 48h. Sem código. Sem dinheiro.", body="Framework: Dia 1 — pesquiso 10 potenciais usuários, mando mensagem, e entrevisto 5. Dia 2 — construo landing page fake com Carrd, rodo anúncio de $20 no Instagram, e mideo taxa de conversão. Se >5% deixam email, a ideia vale a pena. Usei isso pra validar o FairSet antes de escrever uma linha de código.", cta="Comenta VALIDA que eu te mando o framework completo", cta_keyword="VALIDA", category="workflows", visual_format="Framework visual + facecam", source_usa="First Round Review", adaptation_note="Framework usado no FairSet", caption="Valido ideia de produto em 48h. Sem código. Sem dinheiro. ✅", hashtags="#produto #pm #validação #startup #framework"),
        ]
        trends = [
            Trend(title="Claude Code: Vibe Coding para Devs", source="youtube", channel="Alex Finn", url="https://youtube.com/@AlexFinnOfficial", summary="Tutorial completo de Claude Code", brazil_adaptation="PM+Dev: como Claude Code me ajuda a entregar sozinho", adaptation_angle="PM + Dev: entrega sozinho", suggested_format="Reel 60s com tela", priority_score=95),
            Trend(title="Build & Sell n8n AI Agents", source="youtube", channel="Nate Herk", url="https://youtube.com/@nateherk", summary="Curso 8h de automação n8n", brazil_adaptation="Workflow n8n economiza 15h/semana", adaptation_angle="Workflow de n8n no projeto americano", suggested_format="Reel 45s", priority_score=91),
            Trend(title="Claude Code for PMs — 50 use cases", source="newsletter", channel="Lenny's Newsletter", url="https://lennysnewsletter.com", summary="50+ casos de uso de Claude Code", brazil_adaptation="5 casos de uso pra PMs brasileiros", adaptation_angle="5 formas de usar Claude Code como PM", suggested_format="Carrossel LinkedIn", priority_score=88),
            Trend(title="Vibe Coding Explained in 100 Seconds", source="youtube", channel="Fireship", url="https://youtube.com/@Fireship", summary="Conceito de vibe coding em 100s", brazil_adaptation="Vibe coding vai explodir no BR", adaptation_angle="O que é vibe coding e por que vai explodir", suggested_format="Reel 30s", priority_score=82),
            Trend(title="3 AI Habits So Powerful It Feels Like Cheating", source="youtube", channel="Jeff Su", url="https://youtube.com/@JeffSu", summary="3 hábitos de produtividade com IA", brazil_adaptation="3 hábitos adaptados pro BR", adaptation_angle="3 hábitos que me fazem parecer equipe", suggested_format="Reel 60s", priority_score=79),
            Trend(title="The Rundown AI #420: GPT-4o Mini, Claude", source="newsletter", channel="The Rundown AI", url="https://therundown.ai", summary="Notícias diárias de IA", brazil_adaptation="3 notícias mais relevantes", adaptation_angle="3 novidades de IA essa semana", suggested_format="Reel 45s", priority_score=75),
            Trend(title="n8n vs Make.com: Which Wins 2025?", source="youtube", channel="Jono Catliff", url="https://youtube.com/@jono-catliff", summary="Comparativo n8n vs Make", brazil_adaptation="Custo-benefício para brasileiros", adaptation_angle="n8n vs Make: qual eu uso e por quê", suggested_format="Reel 60s", priority_score=73),
            Trend(title="How I'd Learn AI in 2025", source="youtube", channel="Skill Leap AI", url="https://youtube.com/@SkillLeapAI", summary="Roteiro de aprendizado de IA", brazil_adaptation="Roteiro adaptado para brasileiros", adaptation_angle="Se eu começasse do zero, faria apenas 3 coisas", suggested_format="Carrossel", priority_score=70),
        ]
        for s in scripts:
            db.add(s)
        for t in trends:
            db.add(t)
        db.commit()
        print(f"[DB] Seeded {db.query(Script).count()} scripts and {db.query(Trend).count()} trends.")
    except Exception as e:
        print(f"[DB] Seeding error: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    seed_scripts()
