"""Config router — manage API keys securely."""
import os
from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(prefix="/api/config", tags=["config"])
ENV_FILE = ".env"

class ConfigUpdate(BaseModel):
    openai_api_key: str = ""
    apify_api_token: str = ""

def read_env_file() -> dict:
    if not os.path.exists(ENV_FILE):
        return {}
    config = {}
    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if line and "=" in line and not line.startswith("#"):
                key, value = line.split("=", 1)
                config[key] = value
    return config

def write_env_file(config: dict):
    lines = ["# Auto-generated by Fábrica GilCFP\n"]
    for key, value in config.items():
        lines.append(f"{key}={value}\n")
    with open(ENV_FILE, "w") as f:
        f.writelines(lines)

def _mask(value: str) -> str:
    if not value or len(value) < 8:
        return ""
    return value[:6] + "..." + value[-4:]

@router.get("/")
def get_config():
    config = read_env_file()
    return {"openai_api_key": _mask(config.get("OPENAI_API_KEY", "")), "apify_api_token": _mask(config.get("APIFY_API_TOKEN", "")), "has_openai": bool(config.get("OPENAI_API_KEY", "")), "has_apify": bool(config.get("APIFY_API_TOKEN", ""))}

@router.post("/")
def update_config(data: ConfigUpdate):
    config = read_env_file()
    if data.openai_api_key:
        config["OPENAI_API_KEY"] = data.openai_api_key
        os.environ["OPENAI_API_KEY"] = data.openai_api_key
    if data.apify_api_token:
        config["APIFY_API_TOKEN"] = data.apify_api_token
        os.environ["APIFY_API_TOKEN"] = data.apify_api_token
    write_env_file(config)
    return {"message": "Configuração salva com sucesso", "has_openai": bool(config.get("OPENAI_API_KEY", "")), "has_apify": bool(config.get("APIFY_API_TOKEN", ""))}
